databases:
  - name: mi_casita_db
    plan: free
    databaseName: mi_casita_db
    user: admin

services:
  - type: web
    plan: free
    name: mi_casita
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn myblog.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mi_casita_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
